name: Build executable
on: [push]
jobs:
  Build-Linux-Exe:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo code
        uses: actions/checkout@v4
      - name: Download vasm
        run: ./bin/download_vasm.sh
      - name: Build executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6.7'
          spec: 'src/main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'AsimReborn'
          options: --onefile, --name "AsimReborn", --add-binary bin/vasmm68k_mot_linux:bin/
      - name: Showme the .spec
        run: /bin/sh -c 'find . -type f -ls'
