name: Build executable
on:
  push:
    branches:
      - 'main'

env:
  SHELL: bash
  PYTHON_VERSION: '3.12.3'
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  Build-Exe:
    strategy:
      matrix:
        include:
          - os: 'ubuntu-24.04'
            prep: './src/prepare_repo.sh'
            build_vasm: './src/build_vasm.sh'
            build_b68k: './src/build_bare68k.sh'
            build: './src/build.sh'
            dist: 'dist/AsimReborn'
            art:    'asimreborn-lin'
          - os: 'windows-2025'
            prep: '.\src\prepare_repo.bat'
            b68k: '.\lib\bare68k-0.1.2-cp312-cp312-win_amd64.whl'
            vasm: '.\bin\vasmm68k_mot_win.exe'
            build: '.\src\build.bat'
            dist: '.\dist\AsimReborn'
            art:  'asimreborn-win64'
          - os: 'macos-13'
            prep: './src/prepare_repo.sh'
            build_vasm: './src/build_vasm.sh'
            build_b68k: './src/build_bare68k.sh'
            build: './src/build.sh'
            dist: 'dist/AsimReborn'
            art:    'asimreborn-osx_intel'
          - os: 'macos-15'
            prep: './src/prepare_repo.sh'
            build_vasm: './src/build_vasm.sh'
            build_b68k: './src/build_bare68k.sh'
            build: './src/build.sh'
            dist: 'dist/AsimReborn'
            art:    'asimreborn-osx_arm'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
            linux-pip-
            linux-

      - name: Installing GNU coreutils (macOS only)
        if: runner.os == 'macOS'
        run: brew install coreutils

      - name: Installing OS-specific packages
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install --yes libxcb-cursor0 libxcb-shape0 libxcb-image0 \
             libxcb-keysyms1 libxkbcommon-x11-0 libxcb-icccm4 libxcb-xkb1 \
             libxcb-randr0  libxcb-render-util0 libpulse0 libffi8 libpcre3

      - name: Download resources
        run: ${{ matrix.prep }}

      - name: Build vasm (*NIX only)
        if: runner.os != 'Windows'
        run: ${{ matrix.build_vasm }}

      - name: Build bare68k (*NIX only)
        if: runner.os != 'Windows'
        run: ${{ matrix.build_b68k }}

      - name: Install pip dependencies
        run: |
          python -m pip install pip pyinstaller
          pip install -r requirements.txt
          if [ "${{ runner.os }}" != "Windows" ]; then
            pip install bare68k/dist/bare68k-0.1.2*.whl
          else
            set PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
            pip install ${{ matrix.b68k }}
          fi
        shell: bash

      - name: Build executable
        run: ${{ matrix.build }}
      - name: Deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.art }}
          path: ${{ matrix.dist }}
          if-no-files-found: error

