name: Build executable
on: [push]
jobs:
  Build-Linux-Exe:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo code
        uses: actions/checkout@v4
      - name: Download vasm
        run: ./bin/download_vasm.sh
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.6.8'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller pytest
          pip install -r requirements.txt
      - name: Random things
        run: |
          ls -al
          pwd
      - name: Build executable
        run: pyinstaller --clean --onefile --name "AsimReborn" --add-binary bin/vasmm68k_mot_linux:bin/ src/main.py
      - name: Deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asimreborn-linux
          path: dist/AsimReborn
          if-no-files-found: error

