name: Build executable
on:
  push:
    branches:
      - 'main'

env:
  PYTHON_VERSION: '3.12.3'
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  Build-Exe:
    strategy:
      matrix:
        include:
          - os: 'ubuntu-24.04'
            art:    'asimreborn-lin'
          - os: 'windows-2025'
            art:  'asimreborn-win64'
          - os: 'macos-13'
            art:    'asimreborn-osx_intel'
          - os: 'macos-15'
            art:    'asimreborn-osx_arm'

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
            linux-pip-
            linux-

      - name: Installing OS-specific packages
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install --yes libxcb-cursor0 libxcb-shape0 libxcb-image0 \
             libxcb-keysyms1 libxkbcommon-x11-0 libxcb-icccm4 libxcb-xkb1 \
             libxcb-randr0  libxcb-render-util0 libpulse0 libffi8 libpcre3
        if: runner.os == 'macOS'
          run: brew install coreutils

      - name: Download resources
        run: './src/prepare_repo.sh'

      - name: Build vasm
        run: './src/build_vasm.sh'

      - name: Build bare68
        run: './src/build_bare68k.sh'

      - name: Install pip dependencies
        run: |
          python -m pip install pip pyinstaller
          pip install -r requirements.txt
          if [ "${{ runner.os }}" == "Windows" ]; then
            set PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
          fi
          pip install bare68k/dist/bare68k-0.1.2*.whl
        shell: bash

      - name: Build executable
        run: './src/build.sh'

      - name: Deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.art }}
          path: dist/AsimReborn
          if-no-files-found: error

