name: Build executable
on: [push]
jobs:
  Build-Linux-Exe:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      - name: Random things
        run: |
          ls -al
          pwd
      - name: Download resources
        run: ./src/prepare_repo.sh
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller
          pip install -r requirements.txt
          pip install lib/bare68k-0.1.2-cp312-cp312-linux_x86_64.whl
      - name: Build executable
        run: |
          pyinstaller --clean --onedir --name "AsimReborn" --add-binary="bin/vasmm68k_mot_linux:bin/" --add-data="res/DroidSansMono.ttf:res/" src/main.py
      - name: Deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asimreborn-linux
          path: dist/AsimReborn
          if-no-files-found: error

