name: Build executable
on: [push]
jobs:
  Build-Exe:
    strategy:
      matrix:
        include:
          - os: 'ubuntu-20.04'
            prep: './src/prepare_repo.sh'
            build_vasm: './src/build_vasm.sh'
            build_b68k: './src/build_bare68k.sh'
            build: './src/build.sh'
            dist: 'dist/AsimReborn'
            art:    'asimreborn-lin'
          - os: 'windows-latest'
            prep: '.\src\prepare_repo.bat'
            b68k: '.\lib\bare68k-0.1.2-cp312-cp312-win_amd64.whl'
            vasm: '.\bin\vasmm68k_mot_win.exe'
            build: '.\src\build.bat'
            dist: '.\dist\AsimReborn'
            art:  'asimreborn-win64'
          - os: 'darwin-latest'
            prep: './src/prepare_repo.sh'
            build_vasm: './src/build_vasm.sh'
            build_b68k: './src/build_bare68k.sh'
            build: './src/build.sh'
            dist: 'dist/AsimReborn'
            art:    'asimreborn-osx'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checking out repo code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      - name: Installing linux build packages
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install --yes libxcb-cursor0 libxcb-shape0 libxcb-image0 \
             libxcb-keysyms1 libxkbcommon-x11-0 libxcb-icccm4 libxcb-xkb1 \
             libxcb-randr0  libxcb-render-util0
      - name: Download resources
        run: ${{ matrix.prep }}
      - name: Build vasm (UNIX)
        if: runner.os != 'Windows'
        run: ${{ matrix.build_vasm }}
      - name: Build bare68k (UNIX)
        if: runner.os != 'Windows'
        run: ${{ matrix.build_b68k }}
      - name: Install build dependencies (UNIX) 
        if: runner.os != 'Windows'
        run: |
          python -m pip install pip pyinstaller
          pip install -r requirements.txt
          pip install lib/bare68k*.whl
      - name: Install build dependencies windows
        if: runner.os == 'Windows'
        run: |
          set PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
          python -m pip install pip pyinstaller
          pip install -r requirements.txt
          pip install ${{ matrix.b68k }}
      - name: Build executable
        run: ${{ matrix.build }}
      - name: Deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.art }}
          path: ${{ matrix.exec }}
          if-no-files-found: error

